### ISSUE TITLE
`valid` and `invalid` functions disappeared 

### ISSUE THREAD

**Issue by jurcovicova** [vacuumlabs/react-validation#35]
The 0.4.2 version exposed `valid` and `invalid` functions neither of which is available in 0.4.6. I think they were removed by commit https://github.com/vacuumlabs/react-validation/commit/b6cbd552bf176476db7831320f9faf307adcede4

Was the removal intentional? We are using these in our custom validation methods, should we not use them and use something else instead?

**Comment by marcelka** [comment]
Yes, the removal was intentional, as the API for rules was simplified and these functions are not needed anymore. Example:
```
  return value.length >= 5 ? valid() : invalid("Too short!") // old way
  return value.length >= 5 ? null : "Too short!" // new way (null/undefined means there is no error)
```

The most recent version (yet to be published) will understand `null`, `undefined`, `true`, `[]` and `{}` as valid outcomes (equivalent of old `{isValid: true}`). Other return values will be understood as invalid (equivalent of old `{isValid: false, reason: <the return value>}`).

**Comment by jurcovicova** [comment]
Thank you.
